services:

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka

    ports:
      - "9092:9092"

    environment:

      # KRaft Settings
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1

      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093

      # Listeners
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_INTERNAL://0.0.0.0:29092,CONTROLLER://0.0.0.0:29093

      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT

      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL

      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      # Storage + Replication
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

      # Cluster ID
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk

    volumes:
      - kafka_data:/var/lib/kafka/data

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui

    depends_on:
      - kafka

    ports:
      - "8080:8080"

    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092

  spark:
    image: apache/spark:3.5.1

    container_name: spark

    ports:
      - "4040:4040"

    volumes:
      - ./spark_jobs:/opt/spark/jobs
      - ./data:/opt/spark/data
      - ./spark_test:/opt/spark/test

    command: >
      /opt/spark/bin/spark-class
      org.apache.spark.deploy.master.Master

volumes:
  kafka_data: